trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build .\code\LealLang.sln --configuration $(buildConfiguration) 
  displayName: 'Build'