trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration) --project ./code/LealLang/LealLang.csproj
  displayName: 'dotnet build $(buildConfiguration)'